### ISSUE TITLE
Number of Sources

### ISSUE THREAD

**Issue by funkygreg** [Willmac16/homebridge-nuvo#7]
Again, thank you for taking the time for creating this.  I was wondering if it would be possible to include the number of sources, similar to number of zones?  I was also wondering if something would be possible to explode zones, unfortunately my zone 1 is no longer working.

**Comment by Willmac16** [comment]
@funkygreg sorry to get back to you a little slowly. The plugin uses settings on the Nuvo to figure out if zones and sources are enabled. Currently the plugin checks 6 sources since I believe that is the number of sources that Nuvo systems can have. If you have a system with more than 6 sources, I would be happy to add a setting that allows for that.

To enable or disable zones and sources I should be able to add a setting that will have the plugin change that on the Nuvo.

**Comment by Willmac16** [comment]
@funkygreg, version 2.2.0 comes with a nuvo-config tool. When homebridge isn't running, you can run the command`nuvo-config <path_to_port>` then once inside the config prompt run `zone 1 disable` (if it doesn't connect to the port, ensure homebridge isn't running and try running `sudo nuvo-config <path_to_port>`.

**Comment by funkygreg** [comment]
Thanks so much for providing those options :)
